const TYPE = {
  COURSE_DEADLINE: 'COURSE_DEADLINE',
  SYSTEM_ALERT: 'SYSTEM_ALERT',

  ENROLLMENT_CONFIRMED: 'ENROLLMENT_CONFIRMED',
  ENROLLMENT_COMPLETED: 'ENROLLMENT_COMPLETED',

  ASSESSMENT_DEADLINE: 'ASSESSMENT_DEADLINE',
  ASSESSMENT_ASSIGNED: 'ASSESSMENT_ASSIGNED',
  ASSESSMENT_PASSED: 'ASSESSMENT_PASSED',
  ASSESSMENT_FAILED: 'ASSESSMENT_FAILED',
  QUIZ_RESULT: 'QUIZ_RESULT',
};

module.exports = TYPE;
